name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Composer Action
      uses: MilesChou/composer-action@v0.0.1
      
    - name: GitHub Action for npm
      uses: actions/npm@1.0.0

    - name: Run Mix
      run: npm run production

    - name: Run PHPUnit
      run: php7.3 vendor/bin/phpunit
