name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install composer dependencies
      uses: MilesChou/composer-action@master
      run:  install

    - name: Install npm dependencies
      run: npm install

    - name: Run Mix
      run: npm run production

    - name: Run PHPUnit
      run: php7.3 vendor/bin/phpunit
