# Install composer dependencies
action "composer install" {
  uses = "MilesChou/composer-action@master"
  args = "install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist"
}

# Run php-cs-fixer
action "php-cs-fixer" {
  uses = "docker://oskarstark/php-cs-fixer-ga"
}
